# Generated by Codex on 2026-07-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_user_reconciliation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="upload_state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("creating", "Creating"),
                    ("expired", "Expired"),
                    ("duplicating", "Duplicating"),
                    ("converting", "Converting"),
                    ("analyzing", "Analyzing"),
                    ("suspicious", "Suspicious"),
                    ("file_too_large_to_analyze", "File too large to analyze"),
                    ("ready", "Ready"),
                ],
                max_length=25,
                null=True,
            ),
        ),
    ]
