# Generated by Django 5.2.15 on 2026-08-02 20:37

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0030_item_item_creator_size_not_hdel_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("actor_name", models.CharField(max_length=255)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("renamed", "Renamed"),
                            ("description_updated", "Description updated"),
                            ("content_updated", "Content updated"),
                            ("moved", "Moved"),
                            ("trashed", "Moved to trash"),
                            ("restored", "Restored"),
                            ("download_started", "Download started"),
                            ("user_access_created", "User access created"),
                            ("user_access_updated", "User access updated"),
                            ("user_access_revoked", "User access revoked"),
                            ("team_access_created", "Team access created"),
                            ("team_access_updated", "Team access updated"),
                            ("team_access_revoked", "Team access revoked"),
                            ("invitation_created", "Invitation created"),
                            ("invitation_updated", "Invitation updated"),
                            ("invitation_revoked", "Invitation revoked"),
                            ("share_link_created", "Share link created"),
                            ("share_link_updated", "Share link updated"),
                            ("share_link_revoked", "Share link revoked"),
                        ],
                        max_length=32,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="item_activity_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_entries",
                        to="core.item",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item activity",
                "verbose_name_plural": "Item activities",
                "db_table": "drive_item_activity",
                "ordering": ("-created_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["item", "-created_at", "-id"], name="activity_item_created_id_idx"
                    )
                ],
            },
        ),
    ]
