# Generated by Django 5.2.15 on 2026-09-04 23:57

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0030_item_item_creator_size_not_hdel_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="StorageBackend",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("registry_id", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("organization", models.CharField(max_length=255)),
                ("namespace", models.UUIDField(db_index=True, default=uuid.uuid4)),
                ("namespace_root", models.TextField(default="/")),
                ("enabled", models.BooleanField(default=True)),
                ("capacity", models.JSONField(blank=True, default=dict)),
                ("inventory_completed_at", models.DateTimeField(blank=True, null=True)),
                ("inventory_generation", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StorageQuota",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("key", models.CharField(max_length=255, unique=True)),
                ("limit_bytes", models.PositiveBigIntegerField(blank=True, null=True)),
                ("growth_blocked", models.BooleanField(default=False)),
                ("used_bytes", models.PositiveBigIntegerField(default=0)),
                ("reserved_bytes", models.PositiveBigIntegerField(default=0)),
                ("policy_revision", models.CharField(blank=True, default="", max_length=64)),
                ("policy_origin", models.CharField(blank=True, default="", max_length=255)),
                ("policy_version", models.PositiveBigIntegerField(default=0)),
                ("policy_applied_at", models.DateTimeField(blank=True, null=True)),
                ("accounting_ready_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StorageSpace",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("root_path", models.TextField(default="/")),
                ("enabled", models.BooleanField(default=True)),
                ("attribute_to_creator", models.BooleanField(default=False)),
                (
                    "backend",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="spaces",
                        to="core.storagebackend",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="storage_spaces",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StorageUsage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("key", models.CharField(max_length=64, unique=True)),
                ("native_key", models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ("organization", models.CharField(max_length=255)),
                ("path", models.TextField(blank=True, default="")),
                ("provider_identity", models.CharField(blank=True, default="", max_length=255)),
                ("size", models.PositiveBigIntegerField(default=0)),
                ("version", models.CharField(blank=True, default="", max_length=255)),
                ("scope_keys", models.JSONField(default=list)),
                ("observed_at", models.DateTimeField(auto_now=True)),
                ("scan_generation", models.UUIDField(blank=True, db_index=True, null=True)),
                ("attribution_conflict", models.BooleanField(default=False)),
                (
                    "backend",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.storagebackend",
                    ),
                ),
                (
                    "item",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.item",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.storagespace",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StorageReservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("resource_key", models.CharField(db_index=True, max_length=64)),
                ("publication_key", models.CharField(blank=True, default="", max_length=64)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("reserved", "Reserved"),
                            ("writing", "Writing"),
                            ("publishing", "Publishing"),
                            ("committed", "Committed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="reserved",
                        max_length=16,
                    ),
                ),
                ("scope_keys", models.JSONField(default=list)),
                ("target_scope_keys", models.JSONField(blank=True, default=list)),
                ("scope_reservations", models.JSONField(blank=True, default=dict)),
                ("policy_revisions", models.JSONField(blank=True, default=dict)),
                ("previous_size", models.PositiveBigIntegerField(default=0)),
                ("reserved_bytes", models.PositiveBigIntegerField(default=0)),
                ("expected_version", models.CharField(blank=True, default="", max_length=255)),
                ("expires_at", models.DateTimeField()),
                ("publication", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("state__in", ["reserved", "writing", "publishing"])),
                        fields=("resource_key",),
                        name="storage_one_active_publication",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("state__in", ["reserved", "writing", "publishing"]),
                            models.Q(("publication_key", ""), _negated=True),
                        ),
                        fields=("publication_key",),
                        name="storage_one_active_path_publication",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StorageGrant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("team", models.CharField(blank=True, default="", max_length=255)),
                ("path", models.TextField(default="/")),
                ("writable", models.BooleanField(default=False)),
                ("shareable", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grants",
                        to="core.storagespace",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("team", ""), ("user__isnull", False)),
                            models.Q(("user__isnull", True), models.Q(("team", ""), _negated=True)),
                            _connector="OR",
                        ),
                        name="storage_grant_one_principal",
                    )
                ],
            },
        ),
    ]
