# Generated by Django 5.2.15 on 2026-09-05 00:07

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_storage_governance"),
    ]

    operations = [
        migrations.CreateModel(
            name="StorageTransferEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("size", models.PositiveBigIntegerField()),
                ("source_scopes", models.JSONField(default=list)),
                ("target_scopes", models.JSONField(default=list)),
                ("target_attribution", models.JSONField(default=dict)),
                ("applied", models.BooleanField(default=False)),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfer_entries",
                        to="core.storagereservation",
                    ),
                ),
                (
                    "usage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.storageusage"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("operation", "usage"), name="storage_transfer_unique_usage"
                    )
                ],
            },
        ),
    ]
