# Generated by Django 5.2.15 on 2026-09-05 00:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0032_storage_transfers"),
    ]

    operations = [
        migrations.AddField(
            model_name="storagebackend",
            name="attribution_pending",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="storagebackend",
            name="maintenance",
            field=models.BooleanField(default=False),
        ),
    ]
