# Generated by Django 5.2.15 on 2026-09-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0033_storage_maintenance"),
    ]

    operations = [
        migrations.CreateModel(
            name="StorageInventoryEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("namespace", models.UUIDField(db_index=True)),
                ("native_key", models.CharField(db_index=True, max_length=64)),
                ("record", models.JSONField()),
            ],
        ),
    ]
