# Generated by Django 5.2.15 on 2026-09-05 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0036_merge_storage_activity"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="storage_key_prefix",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AddField(
            model_name="item",
            name="storage_backend",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items",
                to="core.storagebackend",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="storage_space",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items",
                to="core.storagespace",
            ),
        ),
        migrations.AddField(
            model_name="storagebackend",
            name="configuration",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="storagebackend",
            name="configuration_generation",
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="storagebackend",
            name="connection_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="storagebackend",
            name="connection_status",
            field=models.CharField(default="unchecked", max_length=32),
        ),
        migrations.AddField(
            model_name="storagebackend",
            name="family",
            field=models.CharField(
                choices=[("mount", "MountProvider"), ("s3", "S3")], default="mount", max_length=8
            ),
        ),
        migrations.AddField(
            model_name="storagebackend",
            name="legacy_s3",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="storagebackend",
            name="managed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="storagebackend",
            name="secret_ciphertext",
            field=models.TextField(blank=True, default="", editable=False),
        ),
        migrations.AddField(
            model_name="storagespace",
            name="root_item",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="root_storage_space",
                to="core.item",
            ),
        ),
    ]
