# Generated by Django 5.2.15 on 2026-09-05 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0037_unified_storage_locations"),
    ]

    operations = [
        migrations.AddField(
            model_name="storagegrant",
            name="manageable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="storagegrant",
            name="root_item",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.item"
            ),
        ),
        migrations.AddField(
            model_name="storagespace",
            name="allow_sharing",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="storagespace",
            name="explicit_access",
            field=models.BooleanField(default=False),
        ),
    ]
