# Generated by Django 5.2.15 on 2026-09-05 11:53

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0038_unified_space_grants"),
    ]

    operations = [
        migrations.CreateModel(
            name="StorageResource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("namespace", models.UUIDField(db_index=True)),
                ("identity_key", models.CharField(max_length=64, unique=True)),
                ("provider_identity", models.CharField(blank=True, max_length=255)),
                ("path", models.TextField()),
                ("parent_path", models.TextField(db_index=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "kind",
                    models.CharField(
                        choices=[("file", "File"), ("folder", "Folder")], max_length=8
                    ),
                ),
                ("size", models.PositiveBigIntegerField(default=0)),
                ("modified_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.CharField(blank=True, max_length=255)),
                ("generation", models.UUIDField(blank=True, null=True)),
                ("missing", models.BooleanField(default=False)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["namespace", "parent_path", "name"],
                        name="core_storag_namespa_eee172_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StorageResourceFavorite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("last_opened_at", models.DateTimeField(blank=True, null=True)),
                ("favorite", models.BooleanField(default=False)),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.storageresource"
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.storagespace"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "resource", "space"), name="storage_resource_user_space"
                    )
                ],
            },
        ),
    ]
