# Generated by Django 5.2.15 on 2026-09-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0039_mounted_resource_index"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="storagemovejob",
            name="storage_one_active_move_request",
        ),
        migrations.AddField(
            model_name="storagemovejob",
            name="kind",
            field=models.CharField(default="native_move", max_length=32),
        ),
        migrations.AddField(
            model_name="storagemovejob",
            name="payload",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="storagemovejob",
            name="state",
            field=models.CharField(
                choices=[
                    ("queued", "queued"),
                    ("running", "running"),
                    ("cleanup", "cleanup"),
                    ("done", "done"),
                    ("failed", "failed"),
                ],
                db_index=True,
                default="queued",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="storagemovejob",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state__in", ["queued", "running", "cleanup"])),
                fields=("actor", "space", "source_path", "destination_path"),
                name="storage_one_active_move_request",
            ),
        ),
    ]
