# Generated by Django 5.2.15 on 2026-09-05 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0042_storage_admin_jobs"),
    ]

    operations = [
        migrations.AddField(
            model_name="storageadminjob",
            name="source_operation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="restore_jobs",
                to="core.storagereservation",
            ),
        ),
        migrations.AlterField(
            model_name="storageadminjob",
            name="kind",
            field=models.CharField(
                choices=[
                    ("inventory", "inventory"),
                    ("reclassify", "reclassify"),
                    ("root", "root"),
                    ("restore", "restore"),
                ],
                max_length=32,
            ),
        ),
    ]
