# Generated by Django 5.2.15 on 2026-09-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0043_storage_restore_jobs"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="storagemovejob",
            name="storage_one_active_move_request",
        ),
        migrations.AddConstraint(
            model_name="storagemovejob",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state__in", ["queued", "running", "cleanup", "conflict"])),
                fields=("actor", "space", "source_path", "destination_path", "kind"),
                name="storage_one_active_move_request",
            ),
        ),
    ]
