# Generated by Django 5.2.15 on 2026-09-05 18:31

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0044_storage_copy_jobs"),
    ]

    operations = [
        migrations.CreateModel(
            name="StorageCopyEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("source", models.JSONField()),
                ("source_id", models.UUIDField()),
                ("kind", models.CharField(max_length=16)),
                ("name", models.CharField(max_length=255)),
                ("target_id", models.UUIDField(blank=True, null=True)),
                ("publication", models.JSONField(blank=True, default=dict)),
                ("enumerated", models.BooleanField(default=False)),
                ("done", models.BooleanField(db_index=True, default=False)),
                (
                    "child_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="folder_entries",
                        to="core.storagemovejob",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="copy_entries",
                        to="core.storagemovejob",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.storagecopyentry",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("job", "source_id"), name="storage_copy_source_once"
                    )
                ],
            },
        ),
    ]
