# Generated by Django 5.2.15 on 2026-09-05 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0045_storage_copy_manifests"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="mountsharelink",
            name="mount_share_link_mount_id_path_unique",
        ),
        migrations.AddField(
            model_name="mountsharelink",
            name="resource",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="share_links",
                to="core.storageresource",
            ),
        ),
        migrations.AddConstraint(
            model_name="mountsharelink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("resource__isnull", True)),
                fields=("mount_id", "normalized_path"),
                name="mount_share_link_mount_id_path_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="mountsharelink",
            constraint=models.UniqueConstraint(
                fields=("resource", "created_by", "mount_id"),
                name="mount_share_link_resource_creator_unique",
            ),
        ),
    ]
