# Generated by Django 5.2.15 on 2026-09-05 19:55

import django.db.models.deletion
from django.db import migrations, models


def merge_favorites(apps, schema_editor):
    """Keep any favorite and the latest visit when collapsing former per-view rows."""
    favorite = apps.get_model("core", "StorageResourceFavorite")
    rows = favorite.objects.using(schema_editor.connection.alias)
    duplicates = (
        rows.values("user_id", "resource_id").annotate(total=models.Count("pk")).filter(total__gt=1)
    )
    for group in duplicates.iterator(chunk_size=200):
        matches = rows.filter(user_id=group["user_id"], resource_id=group["resource_id"])
        kept = matches.order_by("-updated_at", "pk").first()
        values = matches.aggregate(last_opened_at=models.Max("last_opened_at"))
        values["favorite"] = matches.filter(favorite=True).exists()
        rows.filter(pk=kept.pk).update(**values)
        matches.exclude(pk=kept.pk).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0046_mounted_share_resource"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="storageresourcefavorite",
            name="storage_resource_user_space",
        ),
        migrations.AlterField(
            model_name="storageresourcefavorite",
            name="space",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.storagespace",
            ),
        ),
        migrations.RunPython(merge_favorites, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="storageresourcefavorite",
            constraint=models.UniqueConstraint(
                fields=("user", "resource"), name="storage_resource_user"
            ),
        ),
    ]
