# Generated by Django 5.2.15 on 2026-09-08 17:48

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0049_item_share_link_nonce"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="type",
            field=models.CharField(
                choices=[("folder", "Folder"), ("file", "File"), ("docs", "Docs document")],
                default="folder",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="DocsBinding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("document_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("request_key", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("request_hash", models.CharField(blank=True, max_length=64)),
                ("revision", models.PositiveBigIntegerField(default=1)),
                ("applied_revision", models.PositiveBigIntegerField(default=0)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("trash", "Trash"),
                            ("purging", "Purging"),
                            ("purged", "Purged"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("retry_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.CharField(blank=True, max_length=100)),
                ("creation_context", models.JSONField(blank=True, default=dict)),
                (
                    "anchor_space",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="docs_documents",
                        to="core.storagespace",
                    ),
                ),
                (
                    "item",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="docs_binding",
                        to="core.item",
                    ),
                ),
                (
                    "mounted_parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="docs_documents",
                        to="core.storageresource",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["state", "retry_at"], name="core_docsbi_state_2a84f1_idx")
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("anchor_space__isnull", True), ("mounted_parent__isnull", True)
                            ),
                            models.Q(
                                ("anchor_space__isnull", False), ("mounted_parent__isnull", False)
                            ),
                            _connector="OR",
                        ),
                        name="docs_mount_anchor_pair",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("item__isnull", False), ("state", "purged"), _connector="OR"
                        ),
                        name="docs_binding_retained_until_purged",
                    ),
                ],
            },
        ),
    ]
