# Generated by Django 5.2.15 on 2026-09-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0050_docs_document_bindings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="role",
            field=models.CharField(
                choices=[
                    ("reader", "Reader"),
                    ("commenter", "Commenter"),
                    ("editor", "Editor"),
                    ("administrator", "Administrator"),
                    ("owner", "Owner"),
                ],
                default="reader",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="itemaccess",
            name="role",
            field=models.CharField(
                choices=[
                    ("reader", "Reader"),
                    ("commenter", "Commenter"),
                    ("editor", "Editor"),
                    ("administrator", "Administrator"),
                    ("owner", "Owner"),
                ],
                default="reader",
                max_length=20,
            ),
        ),
    ]
