# Generated by Django 5.2.15 on 2026-09-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0051_document_commenter_roles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="link_role",
            field=models.CharField(
                choices=[("reader", "Reader"), ("editor", "Editor"), ("commenter", "Commenter")],
                default="reader",
                max_length=20,
            ),
        ),
    ]
