# Generated by Django 5.2.15 on 2026-09-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0053_docs_command_receipts"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="docsbinding",
            index=models.Index(
                condition=models.Q(("applied_revision__lt", models.F("revision"))),
                fields=["created_at", "id"],
                name="docs_pending_metadata",
            ),
        ),
    ]
