# Generated by Django 5.2.15 on 2026-09-08 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0054_docs_pending_metadata_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storagereservation",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
