# Generated by Django 5.2.15 on 2026-09-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0055_docs_anonymous_quota_actor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="docsbinding",
            name="state",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("preparing", "Preparing content"),
                    ("active", "Active"),
                    ("trash", "Trash"),
                    ("purging", "Purging"),
                    ("purged", "Purged"),
                ],
                default="pending",
                max_length=12,
            ),
        ),
    ]
