# Generated by Django 5.2.15 on 2026-09-09 05:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0057_docs_invitation_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="docsbinding",
            name="sort_order",
            field=models.BigIntegerField(default=0),
        ),
    ]
